config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get  "home/about" => 'home#about'
  resources :books
  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books,dependent: :destroy
  attachment :profile_image

   def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/about_controller.rb
class Home_boutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource)
	end
	def after_sign_out_path_for(resource)
		root_path

	end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
  end
 end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit]

  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
        redirect_to books_path
    end
  end

  def index
  	@books = Book.all
  	@book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
  	@book_new = Book.new
    @book = Book.find(params[:id])
  end

  def new
  	@book = Book.new
    @book = current_user.id
    if @book.save
       flash[:new] = "successfully"
       redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      @users = User.all
      flash[:no] = "error"
      render :index
    end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
  	   flash[:info] = "successfully"
  	   redirect_to book_path(@book.id)
  	else
      @books = Book.all
      @user = current_user
      @users = User.all
      flash[:notice] = "error"
  		render :index
  	end
  end

  def update
  		@book = Book.find(params[:id])
     if @book.update(book_params)
  		flash[:info] = "successfully"
  		redirect_to book_path
  	else
      @books = Book.all
      @user = current_user
      @users = User.all
      flash[:notice] = "error"
      render :index
  	end
  end

  def destroy
  		book = Book.find(params[:id])
  		book.destroy
  		redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :ensure_correct_user , only:[:edit]

	def index
		@book = Book.new
    @user = current_user
    @users = User.all
	end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
    if @user.save
       flash[:info] = "successfully"
       redirect_to user_path(@user.id)
    else
      @users = User.all
      flash[:notice] = "error"
      render :edit
    end
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
  	   flash[:info] = "succsesfully"
  	   redirect_to books_path(@book.id)
  	else@book = Book.all
      @user = current_user
      @users = User.all
      flash[:notice] = "error"
      render :index
    end
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
        redirect_to user_path(current_user)
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>New book</h2>
	<% if flash[:new] %>
		<p><%= flash[:new] %></p>
    <% else flash[:no] %>
		<p><%= flash[:no] %></p>
    <% end %>

	<% if book.errors.any? %>
  		<div id="error_explanation" class="alert alert-danger">
    		<ul>
      		<% book.errors.full_messages.each do |message| %>
       	 		<%= message %>
     	 	<% end %>
   	 		</ul>
 	 	</div>
 	 <% end %>

<%= form_for(book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>opinion</h4>
	<%= f.text_area :body %><br>
	<input type="submit" name="commit" value="Create Book"class="btn btn-primary col-xs-12" date-disable-with="CreateBook">

<% end %>

app/views/books/edit.html.erb
<% if flash[:info] %>
	<p><%= flash[:info] %></p>
<% else flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

	<div class="container">
		<div class= "row" >
			<div class="col-lg-12">
				<h1>Editing Book</h1>
					<% if @book.errors.any? %>
				  		<div id="error_explanation" class="alert alert-danger">
				    		<ul>
				      		<% @book.errors.full_messages.each do |message| %>
				       	 		<%= message %>
				     	 	<% end %>
				   	 		</ul>
				 	 	</div>
				 	<% end %>

				 	<%= form_for(@book) do |f| %>

					<p>title</p>
					<%= f.text_field :title %>
					<p>opinion</p>
					<%= f.text_area :body %>

				<%= f.submit 'Update Book' %><br>
				<% end %>
				<%= link_to "Show", book_path(@book.id) %>|
				<%= link_to "Back", books_path %>
			</div>
		</div>
	</div>

app/views/books/index.html.erb
<div class="container">
	<div class= "row" >
		<div class="col-xs-3">
				<%= render 'users/list', user: @user %>
				<%= link_to " ", edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>

				<%= render 'books/list', book: @book %>
		</div>
		<div class="col-xs-9">
			<table class="table table-striped">
				<colgroup span="4"></colgroup>
				<tr>
					<h3>Books</h3>
				</tr>
					<tr>
						<th>image</th>
						<th>title</th>
						<th>opinion</th>
					</tr>
					<% @books.each do |book| %>
					<tr>
						<td><%= link_to user_path(book.user) do %>
						<%= attachment_image_tag @user, :profile_image,:fill, 60, 60, format: 'jpeg',class: "img-circle pull-left profile-img",  fallback:"no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book.id) %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<%= render 'users/list', user: @user %>

<%= render 'books/list', book: @book %>

app/views/books/show.html.erb
<div class="container">
	<div class= "row" >
		<div class="col-xs-3">
			<% if flash[:info] %>
				<p><%= flash[:info] %></p>
			<% else flash[:notice] %>
				<p><%= flash[:notice] %></p>
			<% end %>

			<h2>User info</h2>
				<%= attachment_image_tag @book.user, :profile_image, fallback:"no_image.jpg" %>
			<table class="table table-striped　style">
				<colgroup span="2"></colgroup>
					<thead>
						<tr>
							<th>name</th>
							<th><%= @book.user.name %></p></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>introduction</td>
							<td><%= @book.user.introduction %></td>
						</tr>
					</tbody>
				</table>
				<h3>name</h3><p><%= @book.user.name %></p>
				<h3>introduction</h3><p><%= @book.user.introduction %></p>
				<%= link_to " ", user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>

			<%= render 'books/list', book: @book_new %>
		</div>
		<div class="col-xs-9">
			<table class="table table-striped">
				<colgroup span="3"></colgroup>
				<thead>
				</thead>
					<tr>
						<h4>Book detail</h4>
						<td><%= link_to user_path(current_user.id) do %>
								<%= attachment_image_tag @user, :profile_image,:fill, 60, 60, format: 'jpeg',class: "img-circle pull-left profile-img",  fallback:"no_image.jpg" %>
								<%=  current_user.name %>
							<% end %>
						</td>
						<td><%= link_to book_path(@book.id) do %>
							<%= @book.title %>
							<% end %>
						</td>
						<td><%= @book.body %></td>
					<% if @book.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book.id),class: "btn-sm btn-success" %></td>
						<td><%= link_to "Destroy", book_path(@book.id), method: :delete,"data-confirm" => "本当に消しますか", class:"btn-sm btn-danger" %></td>
					<% end %>
					</tr>
			</table>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<div class="container">
	<div class= "row" >
		<div class="col-lg-12">

			<h1>Welcom to<span class="glyphicon glyphicon-book"></span><<strong>Bookers!</strong></h1>

		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="container">
	<div class= "row" >
		<div class="col-md-offset-3 col-md-6">
			<ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
				<p><%= flash[:info] %></p>

			<h1>Welcom to<span class="glyphicon glyphicon-book"></span><<strong>Bookers!</strong></h1>
				<p>In<span class="glyphicon glyphicon-book"></span><<strong>Bookers!</strong></p>
				<p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>
		 		<%= link_to "Log in", user_session_path %>
				<%= link_to "Sign Up", new_user_registration_path %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div id="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Home", user_path(current_user.id), class: 'glyphicon glyphicon-home home' %>
              <%= link_to "Users", user_registration_path, class: 'glyphicon glyphicon-user user'%>
              <%= link_to 'Books', books_path, class:'glyphicon glyphicon-book book' %>
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
                 <p><%= flash[:info] %></p>

            <% else %>
              <%= link_to "Home", root_path, class: 'glyphicon glyphicon-home home'  %>
              <%= link_to "About", home_about_path, class: 'glyphicon glyphicon-link about' %>
              <%= link_to "Sign up", new_user_registration_path,  class: 'glyphicon glyphicon-edit sign_up'%>
              <%= link_to "login", user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

      <% if notice %>
        <p><%= notice %></p>
      <% end %>
      <main>
        <%= yield %>
      </main>

    <footer>
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
	<h2>User info</h2>


	<% if flash[:info] %>
		<p><%= flash[:info] %></p>
	<% else flash[:notice] %>
		<p><%= flash[:notice] %></p>
	<% end %>
	<%= attachment_image_tag user, :profile_image,:fill, 60, 60, format: 'jpeg',class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %>
	<table>
		<table class="table table-striped　style">
				<colgroup span="2"></colgroup>
			<tr>
				<th>name</th>
				<td><%= user.name %></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th>introduction</th>
				<td><%= user.introduction %></td>
			</tr>
		</tbody>
	</table>
	<% if user.id == current_user.id %>
	<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_for current_user do |f| %>

<% if flash[:info] %>
	<p><%= flash[:info] %></p>
<% else flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

  <h4>name</h4><%= f.text_field :name %>
  <h4>Image</h4><%= attachment_image_tag @user, :profile_image %>
  <%= f.attachment_field :profile_image, placeholder:"プロフィール画像" %>
  <h4>introduction</h4><%= f.text_field :introduction %><br>

  <%= f.submit 'Update User' %>

 <% end %>

app/views/users/index.html.erb
<div class="container">
	<div class= "row" >
		<div class="col-xs-3">
			<div>
				<%= render 'users/list', user: @user %>
					<%= link_to " ", edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>

				<%= render 'books/list', book: @book %>
			</div>
		</div>
		<div class="col-xs-9">
			<table class="table table-striped">
					<tr>
						<h3>Users</h3>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
					<% @users.each do |user| %>
					<% if flash[:info] %>
						<p><%= flash[:info] %></p>
					<% else flash[:notice] %>
						<p><%= flash[:notice] %></p>
					<% end %>
					<tr>
						<td><%= link_to 'users_path' do %>
							<%= attachment_image_tag @user, :profile_image,:fill, 60, 60, format: 'jpeg',class: "img-circle pull-left profile-img",  fallback:"no_image.jpg" %>
							<% end %>
							</td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(user.id)%></td>
					</tr>
					<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class= "row" >

		<div class= "col-xs-3">
				<%= render 'users/list', user: @user %>
				
				<%= link_to " ",edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
				<%= render 'books/list', book: @book %>
		</div>

		<div class="col-xs-9">
			<table class="table table-striped">
				<tr>
					<h4>Books</h4>
					<th>Title</th>
					<th>opinion</th>
				</tr>
				<% @user.books.each do |book| %>
				<tr>
					<td><%= attachment_image_tag @user, :profile_image,:fill, 60, 60, format: 'jpeg',class: "img-circle pull-left profile-img",  fallback:"no_image.jpg" %></td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</table>
		</div>

	</div>
</div>